### ISSUE TITLE
show: missing parentheses around constructors

### ISSUE THREAD

**Issue by vogler** [whitequark/ppx_deriving#46]
Right now, only constructors with one argument have parenthesis around them. Omitting parenthesis is ok for nullary constructors, but shouldn't be for n-ary ones (as the the output can no longer simply be pasted into the top-level):

 ~~~OCaml
type t = A | B of t | C of t*t [@@deriving show];;
show @@ A;; (* A *)
show @@ B A;; (* (B A) *)
show @@ C (A, A);; (* C (A, A) but should be (C (A, A)) *)
show @@ B (C (A, A));; (* (B C (A, A)) <- problem *)
~~~

**Comment by whitequark** [comment]
@c-cube, I think you altered this last? https://github.com/whitequark/ppx_deriving/commit/8048cf70cb156a776744e14676e6b6610a41809a
I don't quite remember what was the motivation for the change.

**Comment by c-cube** [comment]
Yes indeed, I changed it slightly (I think it was because I found `Some (1)` uglier than `(Some 1)`). I see the problem for nested constructors. A nice thing to have would be to use the old behavior for unary constructors when the argument's type requires it (e.g. another non-nullary constructor, functions, custom printer), but remove parenthesis if the argument doesn't need any (record, primitive).

**Comment by vogler** [comment]
Yes, that's probably better than adding them everywhere.

**Comment by whitequark** [comment]
@c-cube So, would you fix this? If not I will revert your change.

**Comment by jaredly** [comment]
This is still a problem :( :( :(

**Comment by whitequark** [comment]
@jaredly can you fix @vogler's commit above?

**Comment by jaredly** [comment]
Yeah, it works (after I updated it to the current source)

**Comment by jaredly** [comment]
Thanks! I didn't update the tests tho :/ so there's still a bit of work to be done
