### ISSUE TITLE
Derive hash

### ISSUE THREAD

**Issue by modlfo** [whitequark/ppx_deriving#53]
I have found ord and eq very useful, specially with the capability of providing custom functions. In the same fashion it would be great having a deriving hash to be used with Hashtbl.Make.

**Comment by whitequark** [comment]
Yeah. I might do this over the weekend...

**Comment by whitequark** [comment]
Hm, maybe not. There's no usable implementation of OCaml's builtin hash algorithm exported from the stdlib; I will not be providing a hash algorithm inside ppx_deriving since this is not the job of ppx_deriving and the choice of a hash function is not trivial; any external library that provides a hashing module (i.e. mix and finalize functions) can provide a ppx_deriving plugin itself, and will probably have to, since I do not know of any standardized interface for such hashing modules.

Feel free to dissent on the above, however.

**Comment by whitequark** [comment]
Actually, I cannot find any usable hashing library at all, so that will have to be written first.
