### ISSUE TITLE
OCaml 4.03 compatibility

### ISSUE THREAD

**Issue by hcarty** [whitequark/ppx_deriving#80]
There are a handful of changes required, including new constant representations, to be compatible with OCaml 4.03.x.

**Comment by hcarty** [comment]
Thanks!

**Comment by trefis** [comment]
ppx_tools.4.03 is now available in opam, could you also do a release of ppx_deriving working on 4.03?
Thanks in advance.

**Comment by whitequark** [comment]
https://github.com/ocaml/opam-repository/pull/6011

**Comment by trefis** [comment]
Thanks again!

**Comment by whitequark** [comment]
I think the dependency on ppx_tools might need to be tightened. Can you investigate?

**Comment by gasche** [comment]
I am indeed able to build the current master under 4.02.3 after forcing the choice of ppx_tools.4.02.3 rather than what I previously had (ppx_tools.0.99.3). So I guess that `>= 4.02.3` would work -- I assume there is the right conflict-metadata on ppx-tools' side so that it would force `4.03.0` for 4.03 users.

**Comment by whitequark** [comment]
That sounds right to me. Not sure why the metadata wasn't updated--IIRC I did something about it.

**Comment by whitequark** [comment]
Fixed in a02b8f3.
